config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  # Dynamic error pages
  get '/404', to: 'errors#not_found', via: :all
  get '/422', to: 'errors#unacceptable', via: :all
  get '/500', to: 'errors#internal_error', via: :all

  resources :home, only: %i[index show], path: '/' do
    collection do
      get :cherry_show_page
    end
  end
  get '/animal/:id/diet', to: 'home#animal_diet', as: 'animal_diet_api'
  get '/animal/:id/life', to: 'home#animal_life', as: 'animal_life_api'

end

app/models/animal.rb
# frozen_string_literal: true

class Animal < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bovisync_animal.rb
# frozen_string_literal: true

class BovisyncAnimal
  include ActiveModel::Model

  attr_accessor :id,
                :agday, # Age
                :bdate, # Birthdate
                :sireshortnam, # Sire
                :locat, # Location
                :owner, # Owner
                :allfarmslife, # All farms the animal has been to. Comma separated
                :solddied, # Whether the animal was sold or died
                :solddate, # When the animal was sold or died,
                :other2id,
                :apiid, 
                :inherd

  ##
  # Returns the birthdate in Month, Year format
  #
  def birth_date
    bdate && DateTime.parse(bdate).strftime('%B %Y')
  end

  ##
  # Returns the name for the Sire
  #
  def sire_name
    sireshortnam&.titleize
  end

  def total
    corn + byproducts + minerals + forages + milk_lbs
  end

  def corn
    calves_corn + grower_corn + beef_corn
  end

  def calves_corn
    165 * 0.1
  end

  def grower_corn
    225 * 4.4
  end

  def beef_corn
    (agday - 390) * 2.6
  end

  def byproducts
    calf_byproducts + grower_byproducts + beef_byproducts
  end

  def calf_byproducts
    165 * 0.4
  end

  def grower_byproducts
    225 * 1.4
  end

  def beef_byproducts
    agday - 390
  end

  def minerals
    calf_minerals + grower_minerals + beef_minerals
  end

  def calf_minerals
    165 * 3.1
  end

  def grower_minerals
    225 * 2.7
  end

  def beef_minerals
    (agday - 390) * 2.9
  end

  def forages
    calf_forages + grower_forages + beef_forages
  end

  def calf_forages
    165 * 1.8
  end

  def grower_forages
    225 * 11.5
  end

  def beef_forages
    (agday - 390) * 11.5
  end

  ##
  # Milk is in gallons so we convert to lbs here
  #
  def milk_gallons
    165 * 0.7
  end

  def milk_lbs
    gallon_in_pounds = 8.6
    milk_gallons * gallon_in_pounds
  end

  ##
  # Returns an array of all the Farms the animal lived at
  #
  def farms
    farm_names = allfarmslife.split(',').map(&:strip).collect { |farm| farm == 'Royal Feed Lot' ? 'Royal Ranch' : farm }
    farm_names.map do |name|
      Farm.find_or_create_by(name: name)
    end
  end

  def birth_farm
    farm = farms.first
    return farm unless farm.name == 'Royal Dairy'

    Farm.find_or_create_by(name: 'Royal Ranch')
  end

  def death_farm
    farms.last
  end

  def conversion_farm
    Farm.find_or_create_by(name: "Abe's Kosher Meats") do |farm|
      farm.city = 'Burley'
      farm.state = 'ID'
    end
  end

  def dead?
    solddied == 1
  end

  def sold?
    solddied == 0
  end

  def death_date
    solddate && DateTime.parse(solddate).strftime('%B %Y')
  end

  def Co2Emitted 
      agday*0.00370583

  end
  def Co2Sequested
    agday*0.004010244
  end
  def Co2Total
    (agday*0.00370583)-(agday*0.004010244)
  end
  ##
  # Beef grade is stored under +other2id+
  #
  def grade
    other2id
  end
end

app/models/cherry.rb
class Cherry < ApplicationRecord
end

app/models/farm.rb
# frozen_string_literal: true

class Farm < ApplicationRecord
  def to_s
    name
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: :not_found }
      format.json { render json: { error: 'Resource not found' }, status: :not_found }
    end
  end

  def unacceptable
    respond_to do |format|
      format.html { render status: :unprocessable_entity }
      format.json { render json: { error: 'Params unacceptable' }, status: :unprocessable_entity }
    end
  end

  def internal_error
    respond_to do |format|
      format.html { render status: :internal_server_error }
      format.json { render json: { error: 'Internal server error' }, status: :internal_server_error }
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  caches_action :show, :animal_diet
  caches_action :index, unless: -> { params[:id].present? }

  def index
   if params[:id].present?
    redirect_to home_url(params[:id]) if params[:product_id]=="1"
    redirect_to cherry_show_page_home_index_url(temp: params[:id]) if params[:product_id]=='2'
   end
  end

  def show
      bovisync = Bovisync.new
      animal = Animal.find_by!(eartag: params[:id])
      animal_id = animal.bovisync_id
      report = bovisync.report(
        animal: animal_id,
        item: ['AGDAY']
      )

      report_data = report[animal_id.to_sym]

      # Clean data if available
      if report_data.present?
        report_data[:id] = animal_id
        # Downcase keys for model
        report_data.transform_keys!(&:downcase)
      end

      raise ActionController::RoutingError, 'Not Found' if report_data.blank?
      logger.debug "report_data attributes in action 'show' are #{report_data}"
      @animal = BovisyncAnimal.new(report_data)
  end

  def animal_diet
    report_data = Rails.cache.fetch("animals/#{params[:id]}/diet") do
      bovisync = Bovisync.new
      animal = Animal.find_by!(eartag: params[:id])
      animal_id = animal.bovisync_id
      report = bovisync.report(
        animal: animal_id,
        item: ['AGDAY']
      )

      report_data = report[animal_id.to_sym]

      # Clean data if available
      if report_data.present?
        report_data[:id] = animal_id
        # Downcase keys for model
        report_data.transform_keys!(&:downcase)
      end
      report_data
    end
    # Raise 404 if animal is not found
    raise ActionController::RoutingError, 'Not Found' if report_data.blank?
    logger.debug "report_data attributes in action 'animal_diet' are #{report_data}"
    @animal = BovisyncAnimal.new(report_data)
    render layout: false
  end

  def animal_life
    report_data = Rails.cache.fetch("animals/#{params[:id]}/life") do
      bovisync = Bovisync.new
      animals = Animal.where(eartag: params[:id])
      animal_ids = animals.pluck(:bovisync_id)

      report = report_data = animal_id = nil
      animal_ids.each do |aid|
        report = bovisync.report(
          animal: aid,
          item: ['BDATE', # Birth date
                 'LOCAT', # Location
                 'Owner', # Farm owner
                 'SireShortNam', # Sire Name
                 'SoldDate', # Date animal was sold or died
                 'AllFarmsLife', # All farms the animal has lived at
                 'Other2ID'] # Beef Grade
        )
        report_data = report[aid.to_sym]

        break if report_data&.dig(:Other2ID).present?
      end

      # Clean data if available
      if report_data.present?
        report_data[:id] = animal_id
        # Downcase keys for model
        report_data.transform_keys!(&:downcase)
      end
      report_data
    end
    # Raise 404 if animal is not found
    raise ActionController::RoutingError, 'Not Found' if report_data.blank?
    logger.debug "report_data attributes in action 'animal_life' are #{report_data}"
    @animal = BovisyncAnimal.new(report_data)
    render layout: false
  end

  def cherry_show_page
    begin
      @cherry = Cherry.find(params[:temp])
    rescue ActiveRecord::RecordNotFound => e
      raise ActionController::RoutingError, 'Not Found'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cherry_helper.rb
module CherryHelper
end

app/views/home/animal_diet.html.erb
<li class="w-full sm:w-1/2 xl:w-1/5 mb-8">
  <div class="circle-progress-box p-4">
    <div class="circle-progress relative max-w-full w-40 mx-auto">
      <svg class="w-full text-primary-base transform -rotate-90" viewbox="0 0 140 140">
        <linearGradient id="circle-gradient-0" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stop-color="#054A29" />
          <stop offset="100%" stop-color="#2A9134" />
        </linearGradient>
        <circle cx="70" cy="70" r="64" stroke="#DEDACA" stroke-width="10" fill="none">
        </circle>
        <circle stroke="url(#circle-gradient-0)" cx="70" cy="70" r="64"
          stroke-width="10" fill="none" stroke-linecap="round" stroke-dasharray="400"
          stroke-dashoffset="<%= 400 - (@animal.forages / @animal.total) * 400 %>">
        </circle>
      </svg>
      <h5 class="absolute w-full h-full flex items-center justify-center text-2xl z-10 top-0 left-0 text-gray-800">
        <%= number_with_precision(@animal.forages, precision: 1, strip_insignificant_zeros: true, delimiter: ',') %> <sub class="text-sm pl-1">lbs</sub></h5>
    </div>
    <h4 class="mt-4 text-gray-800">Grass & Local Forages</h4>
  </div>
</li>
<li class="w-full sm:w-1/2 xl:w-1/5 mb-8">
  <div class="circle-progress-box p-4">
    <div class="circle-progress relative max-w-full w-40 mx-auto">
      <svg class="w-full text-primary-base transform -rotate-90" viewbox="0 0 140 140">
        <linearGradient id="circle-gradient-1" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stop-color="#054A29" />
          <stop offset="100%" stop-color="#2A9134" />
        </linearGradient>
        <circle cx="70" cy="70" r="64" stroke="#DEDACA" stroke-width="10" fill="none">
        </circle>
        <circle stroke="url(#circle-gradient-1)" cx="70" cy="70" r="64"
          stroke-width="10" fill="none" stroke-linecap="round" stroke-dasharray="400"
          stroke-dashoffset="<%= 400 - (@animal.byproducts / @animal.total) * 400 %>">
        </circle>
      </svg>
      <h5 class="absolute w-full h-full flex items-center justify-center text-2xl z-10 top-0 left-0 text-gray-800">
        <%= number_with_precision(@animal.byproducts, precision: 1, strip_insignificant_zeros: true, delimiter: ',') %> <sub class="text-sm pl-1">lbs</sub></h5>
    </div>
    <h4 class="mt-4 text-gray-800">Recycled Byproducts</h4>
  </div>
</li>
<li class="w-full sm:w-1/2 xl:w-1/5 mb-8">
  <div class="circle-progress-box p-4">
    <div class="circle-progress relative max-w-full w-40 mx-auto">
      <svg class="w-full text-primary-base transform -rotate-90" viewbox="0 0 140 140">
        <linearGradient id="circle-gradient-2" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stop-color="#054A29" />
          <stop offset="100%" stop-color="#2A9134" />
        </linearGradient>
        <circle cx="70" cy="70" r="64" stroke="#DEDACA" stroke-width="10" fill="none">
        </circle>
        <circle stroke="url(#circle-gradient-2)" cx="70" cy="70" r="64"
          stroke-width="10" fill="none" stroke-linecap="round" stroke-dasharray="400"
          stroke-dashoffset="<%= 400 - (@animal.corn / @animal.total) * 400 %>">
        </circle>
      </svg>
      <h5 class="absolute w-full h-full flex items-center justify-center text-2xl z-10 top-0 left-0 text-gray-800">
        <%= number_with_precision(@animal.corn, precision: 1, strip_insignificant_zeros: true, delimiter: ',') %> <sub class="text-sm pl-1">lbs</sub></h5>
    </div>
    <h4 class="mt-4 text-gray-800">Corn</h4>
  </div>
</li>
<li class="w-full sm:w-1/2 xl:w-1/5 mb-8">
  <div class="circle-progress-box p-4">
    <div class="circle-progress relative max-w-full w-40 mx-auto">
      <svg class="w-full text-primary-base transform -rotate-90" viewbox="0 0 140 140">
        <linearGradient id="circle-gradient-3" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stop-color="#054A29" />
          <stop offset="100%" stop-color="#2A9134" />
        </linearGradient>
        <circle cx="70" cy="70" r="64" stroke="#DEDACA" stroke-width="10" fill="none">
        </circle>
        <circle stroke="url(#circle-gradient-3)" cx="70" cy="70" r="64"
          stroke-width="10" fill="none" stroke-linecap="round" stroke-dasharray="400"
          stroke-dashoffset="<%= 400 - (@animal.minerals / @animal.total) * 400 %>">
        </circle>
      </svg>
      <h5 class="absolute w-full h-full flex items-center justify-center text-2xl z-10 top-0 left-0 text-gray-800">
        <%= number_with_precision(@animal.minerals, precision: 1, strip_insignificant_zeros: true, delimiter: ',') %> <sub class="text-sm pl-1">lbs</sub></h5>
    </div>
    <h4 class="mt-4 text-gray-800">Concentrates & Mineral</h4>
  </div>
</li>
<li class="w-full sm:w-1/2 xl:w-1/5 mb-8">
  <div class="circle-progress-box p-4">
    <div class="circle-progress relative max-w-full w-40 mx-auto">
      <svg class="w-full text-primary-base transform -rotate-90" viewbox="0 0 140 140">
        <linearGradient id="circle-gradient-4" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" stop-color="#054A29" />
          <stop offset="100%" stop-color="#2A9134" />
        </linearGradient>
        <circle cx="70" cy="70" r="64" stroke="#DEDACA" stroke-width="10" fill="none">
        </circle>
        <circle stroke="url(#circle-gradient-4)" cx="70" cy="70" r="64"
          stroke-width="10" fill="none" stroke-linecap="round" stroke-dasharray="400"
          stroke-dashoffset="<%= 400 - (@animal.milk_lbs / @animal.total) * 400 %>">
        </circle>
      </svg>
      <h5 class="absolute w-full h-full flex items-center justify-center text-2xl z-10 top-0 left-0 text-gray-800">
        <%= number_with_precision(@animal.milk_gallons, precision: 1, strip_insignificant_zeros: true, delimiter: ',') %> <sub class="text-sm pl-1">gal</sub></h5>
    </div>
    <h4 class="mt-4 text-gray-800">Calves Milk</h4>
  </div>
</li>

app/views/home/animal_life.html.erb
<div class="w-full sm:w-1/2 lg:w-1/4 pb-4 mb-4 border-solid border-b sm:border-l sm:border-b-0 border-gray-550 border-opacity-50 sm:px-5">
  <h4 class="text-gray-800 text-xl mb-2">Origin</h4>
  <p class="mb-2">
    <%= @animal.birth_date %> at <br>
    <%= @animal.birth_farm %>
    <% if @animal.birth_farm.city.present? || @animal.birth_farm.state.present? %>
      <br> <%= [@animal.birth_farm.city, @animal.birth_farm.state].compact.join(', ') %>
    <% end %>
  </p>
</div>
<div class="w-full sm:w-1/2 lg:w-1/4 pb-4 mb-4 border-solid border-b sm:border-l sm:border-b-0 border-gray-550 border-opacity-50 sm:px-5">
  <h4 class="text-gray-800 text-xl mb-2">Growth</h4>
  <p class="mb-2">
    Grown at <%= @animal.birth_farm %>
    <% if @animal.birth_farm.city.present? || @animal.birth_farm.state.present? %>
      <br> <%= [@animal.birth_farm.city, @animal.birth_farm.state].compact.join(', ') %>
    <% end %>
  </p>
  <p class="mb-2">
    Finished at <%= @animal.death_farm %>
    <% if @animal.death_farm.city.present? || @animal.death_farm.state.present? %>
      <br> <%= [@animal.death_farm.city, @animal.death_farm.state].compact.join(', ') %>
    <% end %>
  </p>
  <ul class="list-disc ml-5">
    <li>Humanely Raised</li>
  </ul>
</div>
<div class="w-full sm:w-1/2 lg:w-1/4 pb-4 mb-4 border-solid border-b sm:border-l sm:border-b-0 border-gray-550 border-opacity-50 sm:px-5">
  <h4 class="text-gray-800 text-xl mb-2">Sire & Dam</h4>
  <p class="mb-2">Sire: <%= @animal.sire_name %></p>
  <p class="mb-2">
    Dam: <%= @animal.birth_farm %>
    <% if @animal.birth_farm.city.present? || @animal.birth_farm.state.present? %>
      <br> <%= [@animal.birth_farm.city, @animal.birth_farm.state].compact.join(', ') %>
    <% end %>
  </p>
</div>
<div class="w-full sm:w-1/2 lg:w-1/4 pb-4 mb-4 border-solid border-b sm:border-l sm:border-b-0 border-gray-550 border-opacity-50 sm:px-5">
  <h4 class="text-gray-800 text-xl mb-2">Conversion</h4>
  <p class="mb-2">
    <%= "#{@animal.death_date} at <br>".html_safe if @animal.death_date %>
    <%= @animal.conversion_farm %>
    <% if @animal.conversion_farm.city.present? || @animal.conversion_farm.state.present? %>
      <br> <%= [@animal.conversion_farm.city, @animal.conversion_farm.state].compact.join(', ') %>
    <% end %>
  </p>
  <ul class="list-disc ml-5">
    <li>Hormone Free</li>
    <li>Antibiotic Free</li>
    <% if @animal.grade %>
      <li>Grade: <%= @animal.grade %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="ft-footer py-10">
  <div class="container mx-auto">
    <div class="text-center">
       <p><a href="mailto:contact@farmtracer.com">shaina@farmtracer.com</a> | (509) 899-7646<br>P.O. Box 85 Royal City, Washington 99357</p> 
      <div class="flex justify-center mt-4">
        <a href="" class="w-6 h-6 block m-2 opacity-50 hover:opacity-100 transition-all duration-300">
        <%= image_tag('facebook-f-brands.svg',:alt=>"",:class =>"max-h-full mx-auto")  %>
        </a>
        <a href="" class="w-6 h-6 block m-2 opacity-50 hover:opacity-100 transition-all duration-300">
        <%= image_tag('linkedin-in-brands.svg',:alt=>"",:class =>"max-h-full mx-auto")  %>
        </a>
        <a href="" class="w-6 h-6 block m-2 opacity-50 hover:opacity-100 transition-all duration-300">
        <%= image_tag('twitter-brands.svg',:alt=>"",:class =>"max-h-full mx-auto")  %>
        </a>
        <a href="" class="w-6 h-6 block m-2 opacity-50 hover:opacity-100 transition-all duration-300">
        <%= image_tag('instagram-brands.svg',:alt=>"",:class =>"max-h-full mx-auto")  %>
        </a>
      </div>
    </div>
  </div>
  <div
    class="px-5 lg:px-8 xl:px-12 py-3 flex flex-wrap items-center text-center sm:justify-between mt-5 md:mt-8">
    <div class="w-full sm:w-auto">© <%= Time.zone.now.year %> FarmTracer</div>
    <div class="w-full sm:w-auto">Website by <a href="https://embrk.com/">embrk</a>.</div>
  </div>
</footer>
<style>
  html {
  scroll-behavior: smooth;
}
</style>
<script>


  // TODO: Move this to the correct rails way to do this
  mobileNavigation = document.getElementById('mobileNavigation');
  mobileNavigationOpen = document.getElementById('mobileNavigationButton');
  mobileNavigationClose = document.getElementById('mobileNavigationClose');

  mobileNavigationOpen.addEventListener("click", function () {
  mobileNavigation.classList.add('is-open');
  });

  mobileNavigationClose.addEventListener("click", function () {
  mobileNavigation.classList.remove('is-open');
  });
</script>

app/views/layouts/_head.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Farm Tracer</title>

  <%= favicon_link_tag 'apple-touch-icon.png', sizes: '180x180', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= favicon_link_tag 'favicon-32x32.png', sizes: '32x32',type: 'image/png' %>
  <%= favicon_link_tag 'favicon-16x16.png', sizes: '16x16',type: 'image/png' %>
  <%= favicon_link_tag 'safari-pinned-tab.svg', color:'#2a9134', sizes: '16x16',type: 'image/png' %>
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800&family=Nunito+Sans&display=swap" %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://code.highcharts.com/highcharts.js"></script>
  <script src="https://code.highcharts.com/highcharts-more.js"></script>
  <script src="https://code.highcharts.com/modules/solid-gauge.js"></script>

</head>

app/views/layouts/_header.html.erb
<header class="ft-header">
  <div class="px-5 py-3 lg:px-8 xl:px-12 flex items-center justify-between">
    <%= link_to home_index_url class: 'flex-shrink-0' do %>
      <%= image_tag('logo-with-text.svg', class: 'Farmtracer Logo')  %>
    <% end %>
    <nav class="ft-top-nav">
      <button id="mobileNavigationButton"
        class="w-8 border-none outline-none bg-none xl:hidden group focus:outline-none">
        <span class="h-1 w-full bg-gray-800 block my-2 group-hover:bg-primary-base"></span>
        <span class="h-1 w-full bg-gray-800 block my-2 group-hover:bg-primary-base"></span>
      </button>
      <ul id="mobileNavigation"
        class="main-navigation flex items-center transition-all duration-500 ease-linear">
        <li class="xl:hidden">
          <button id="mobileNavigationClose"
            class="w-8 h-8 border-none outline-none bg-none absolute top-0 right-0 mt-4 mr-4 group focus:outline-none">
            <span
              class="h-1 w-full bg-gray-800 absolute top-1/2 left-0 group-hover:bg-primary-base transform rotate-45 origin-center"></span>
            <span
              class="h-1 w-full bg-gray-800 absolute top-1/2 left-0 group-hover:bg-primary-base transform -rotate-45 origin-center"></span>
          </button>
        </li>
        <li class="px-3 py-2 xl:px-4 xl:py-0">
          <%= link_to 'How it works', home_index_url(anchor: 'how_it_works'), class: 'font-display font-medium text-primary-dark hover:text-primary-base text-2xl xl:text-lg' %>
        </li>
        <li class="px-3 py-2 xl:px-4 xl:py-0">
          <%= link_to 'Why FarmTracer', home_index_url(anchor: 'why_farm_tracer'), class: 'font-display font-medium text-primary-dark hover:text-primary-base text-2xl xl:text-lg' %>
        </li>
        <!-- <li class="px-3 py-2 xl:px-4 xl:py-0">
          <%= link_to 'Meet our farms', home_index_url, class: 'font-display font-medium text-primary-dark hover:text-primary-base text-2xl xl:text-lg' %>
        </li> -->
        <li class="px-3 py-2 xl:px-4 xl:py-0">
          <%= link_to 'About', home_index_url(anchor: 'about'), class: 'font-display font-medium text-primary-dark hover:text-primary-base text-2xl xl:text-lg' %>
        </li>
         <li class="px-3 py-2 xl:px-4 xl:py-0">
          <%= link_to 'Team', home_index_url(anchor: 'get_know_team'), class: 'font-display font-medium text-primary-dark hover:text-primary-base text-2xl xl:text-lg' %>
        </li>
        <li class="px-3 py-2 xl:px-4 xl:py-0">
          <%= link_to 'Contact', home_index_url(anchor: 'contact'), class: 'font-display font-medium text-primary-dark hover:text-primary-base text-2xl xl:text-lg' %>
        </li>
        <li class="px-3 py-2 xl:px-4 xl:py-0 hidden xl:inline-block">
          <span>|</span>
        </li>
        <li class="px-3 py-2 xl:px-4 xl:py-0">
          <%= link_to 'Become Certified', home_index_url(anchor: 'contact'), class: 'font-display font-medium text-primary-dark hover:text-primary-base text-2xl xl:text-lg' %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head" %>
  <body class="font-body text-gray-600" data-controller="icons">
    <main class="ft-main flex flex-col min-h-screen">
      <%= render "layouts/header" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </main>
  </body>
</html>